stages:
  - docker-build
docker_build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: sridhar281994/buildozer-android:v10
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE