stages:
  - build
  - deploy
variables:
  DOCKER_IMAGE: sridhar281994/buildozer-android:v10
  BUILDOZER_ALLOW_ROOT: 1
before_script:
  - apk add --no-cache bash git
build_apk:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo "Pushing Docker image..."
    - docker push $DOCKER_IMAGE
deploy_apk:
  stage: deploy
  image: $DOCKER_IMAGE
  script:
    - echo "Building APK..."
    - pip install --upgrade pip buildozer cython
    - buildozer android debug
  artifacts:
    paths:
      - bin/*.apk
    when: always
