image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
stages:
  - build
build-apk:
  stage: build
  script:
    - apk add --no-cache bash git
    - docker build -t kivy-builder .
    - docker run --rm -v $CI_PROJECT_DIR:/app kivy-builder /bin/sh -c "pip install --upgrade pip buildozer cython && BUILDOZER_ALLOW_ROOT=1 buildozer android debug"
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
