image: sridhar281994/buildozer-android:v10
stages:
  - build
variables:
  ANDROID_HOME: "/root/.buildozer/android/platform/android-sdk"
build-apk:
  stage: build
  script:
    - pip install --upgrade pip buildozer cython
    # Patch Buildozer to auto-accept root prompt
    - sed -i "s/cont = input('Are you sure you want to continue y\/n\?')/cont = 'y'/" \
        $(python3 -c "import buildozer; print(buildozer.__file__)")
    - buildozer android debug
  artifacts:
    paths:
      - bin/*.apk

