image: sridhar281994/buildozer-android:v10
stages:
  - build
variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
before_script:
  - pip install --upgrade buildozer cython
build-apk:
  stage: build
  script:
    - buildozer android debug
  artifacts:
    paths:
      - bin/*.apk
    expire_in: 1 week
