image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_IMAGE: kivy-builder
stages:
  - build
  - apk
before_script:
  - apk add --no-cache bash git
build-image:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .
build-apk:
  stage: apk
  needs: [build-image]
  script:
    - docker run --rm -v $CI_PROJECT_DIR:/app $DOCKER_IMAGE /bin/sh -c "
        pip install --upgrade pip buildozer cython &&
        BUILDOZER_ALLOW_ROOT=1 buildozer android debug
      "
  artifacts:
    paths:
      - bin/*.apk
    expire_in: 1 week
