name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Docker (for GitHub-hosted runners)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Run Buildozer Docker image to generate APK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e BUILDOZER_ALLOW_ROOT=1 \
            sridhar281994/buildozer-android:v11 \
            buildozer --allow-root android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
