name: Build APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build -t kivy-builder .
        docker tag kivy-builder:latest ${{ secrets.DOCKER_USERNAME }}/kivy-builder:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/kivy-builder:latest
    - name: Run Buildozer
      run: |
        docker run --rm -v ${{ github.workspace }}:/app ${{ secrets.DOCKER_USERNAME }}/kivy-builder:latest \
        /bin/sh -c "BUILDOZER_ALLOW_ROOT=1 buildozer android debug"
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: bin/*.apk
